export enum RoutesEnum {
  HOME = '/',
  LOGIN = '/login',
  SIGNUP = '/signup',
  DASHBOARD = '/dashboard',
  USERS = '/dashboard/users',
  ROLES = '/dashboard/roles',
  PERMISSIONS = '/dashboard/permissions',
  PRODUCTS = '/dashboard/products',
  CATEGORIES = '/dashboard/categories',
  COUPONS = '/dashboard/coupons',
  SETTINGS = '/dashboard/settings',
  DEMO = '/demo',
  CART = '/cart',
  CHECKOUT = '/checkout',
  CHECKOUT_RESULT = '/checkout/result',
  MY_ORDERS = '/account/orders',
  MY_PRODUCTS = '/account/products',
  MY_SALES = '/account/sales',
  MY_COUPONS = '/account/coupons',
}
